# A workflow to run the generate_teams.py script in the CI weekly and create a pull request
name: Generate teams for PyBaMM

on:
  schedule:
    # Run every Monday at 03:15 AM UTC
    - cron: "15 3 * * 1"
  workflow_dispatch:

jobs:
  generate-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive

      - name: Setup Python
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Generate teams page(s)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uvx nox -s teams

      # Will exit silently if there are no changes
      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          # Commit details
          commit-message: "Automated update for the Teams page"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          # Pull request details
          branch: "create-pull-request/generate-teams"
          branch-suffix: timestamp
          delete-branch: true
          base: "main"
          title: "Update teams weekly"
          body: "This pull request was automatically created by the CI workflow `teams.yml`."
          labels: "auto-generated"
          reviewers: |
            agriyakhetarpal
            Saransh-cpp
            valentinsulzer
            rtimms
          draft: false
